### ISSUE TITLE
No `VideoLibrary.Scan` method

### ISSUE THREAD

**Issue by Chiggy-Playz** [matthuisman/docker-kodi-headless#12]
Hello. I started this container yesterday by doing:
```
sudo docker run 
-d --name=kodi-headless 
--restart unless-stopped 
-v /kodi:/config/.kodi 
-e TZ=Asia/Calcutta 
-p 8080:8080 
-p 9090:9090 
-p 9777:9777/udp 
matthuisman/kodi-headless:Matrix
```

I had manually created the `/kodi` dir on my pi before starting the container.
After starting the container, I went to `/kodi/userdata` and edited advancedsettings.xml. 
I also pasted my sources.xml file there
I put in my host ip and the uname and password
I also changed the services > devicename setting (I hope this is fine) in the advancedsettings.xml

It runs successfully and i can access the web ui at `pi_ip:8080` and in the movies section I can see all the movies on my database
but when I do a get request to `kodi:kodi@192.168.1.105:8080/jsonrpc`, in the `methods` key of the response, theres no `VideoLibrary.Scan` method. How do I trigger a scan?

**Comment by Chiggy-Playz** [comment]
Update:
Doing `Scan Video Library` option from the ui triggers a scan, but i get a notification saying the scan is completed in just 2-3 seconds. That doesnt seem right. I checked `sudo docker logs -f kodi-headless` but I dont think thats the correct place for kodi logs. Where can I check logs?

**Comment by matthuisman** [comment]
You need to familiarize yourself with how docker works. You probably need
to mount the hosts path where media is into the container for starters. And
the log will be inside the container etc

**Comment by matthuisman** [comment]
With smb you shouldn't need to mount anything from host. I suspect your missing the scraper. Can be hard getting them working. Especially the new python scrapers. Log is inside the container. Look at source code. Should tell you where abouts. Can't remember of top of my head

**Comment by Chiggy-Playz** [comment]
I looked at the source code and I found something which I believe logs things, but I didnt find a path or anything. Also, container logs (`sudo docker logs -f kodi-headless`) show nothing when I go to the webui and click on scan library. 
Also, why is getting the scraper hard? How does one install it?
Sorry for bothering you with such questions.

**Comment by matthuisman** [comment]
Well you cant install add-ons via Kodi web interface. So you need.to
manually copy them and their dependencies into the Kodi addons directory
etc.

**Comment by Chiggy-Playz** [comment]
So I solved it. It was just me being an idiot. I had forgotten to paste my passwords.xml file in userdata and it was having issues finding it. It works now. Thank You!

**Comment by matthuisman** [comment]
Oh, great to hear that :)
