### ISSUE TITLE
Request: add libbluray support

### ISSUE THREAD

**Issue by maff76** [matthuisman/docker-kodi-headless#13]
HI there

I think this maybe a Unraid problem, have everything setup great and almost working 100% except i cannot scan in blu ray rips in folder structure it ignores them completely apart from a message saying trying to load setting definitions from old format..., but iso and mkv scan in fine, i have found this post from 2010 

"Yeah, Linux lacks that support currently. The libraries are being worked on, I bet it will work by the next stable release.
Your options basically are use Windows, or point to m2ts files instead (those scrape fine)."

https://forum.kodi.tv/showthread.php?tid=88101

so i am assume Unraid doesn't include those libs or not in the container?

**Comment by matthuisman** [comment]
Oh I don't think we build headless with libbluray.  Look in the docker file

**Comment by maff76** [comment]
i think i found the libs folder and doesn't look like it is there :(, is there any chance of an updated version to include it?

**Comment by matthuisman** [comment]
Yes, I can look at adding it :)

**Comment by maff76** [comment]
Hi Matt

i have done some more experimenting and i think it is a unraid problem or permission problem or I don't know lol as it can identify blurays and scan them in, but i have to go to the BDMV folder and initiate the scan by trying to bring up the info, during a library scan it checks for example Die hard but stops there it doesn't go down any more folder levels so finds no BDMV folder or index.BDMV, i have found a work around which is to exclude all the folders it shouldn't add during  the scan and turn on recursive scanning, so wanted to save you time hopefully in adding things i don't believe it needs now and i just need to try some more things

**Comment by matthuisman** [comment]
ok, im actually not building with libbluray as I assumed it was just used for playback.
so let me know
