### ISSUE TITLE
Adding addons 

### ISSUE THREAD

**Issue by Ton-O** [matthuisman/docker-kodi-headless#17]
Great work!

One question: how can I add additional addons to KODI? I see the add-on menu-item, but it doesn't allow much interaction.
I've managed to get one or 2 added by git clone, but things get a bit complex when dealing with dependencies that need to be resolved.

**Comment by matthuisman** [comment]
Adding addons is tricky. Currently easiest is install them on another instance eg. On windows. Then copy over the folder.

Ideally I could add a cmdline tool for adding addons that uses the Kodi API. However, pretty sure they show a yes / no dialog so I'd need to patch Kodi to always be yes

**Comment by Ton-O** [comment]
Thanks for the prompt reply!
Well, it would be great if you could add such a cmdline tool; if time permits. 
For now,I’ll continue the way of copying them.

**Comment by matthuisman** [comment]
my new Nexus images will contain this new patch:
 https://github.com/matthuisman/docker-kodi-headless/blob/Nexus/patches/install_addons.patch
 
 It removes the yes / no when installing an add-on via Python or api etc and just installs them in the background (like how update addons would)

**Comment by Ton-O** [comment]
Thanks! Will try today or tomorrow and report back!

**Comment by matthuisman** [comment]
and now added a cli tool (yet to be tested)
https://github.com/matthuisman/docker-kodi-headless/blob/Nexus/root/usr/bin/install_addon

**Comment by matthuisman** [comment]
added how-to install addons to readme:
https://github.com/matthuisman/docker-kodi-headless/blob/master/README.md#install-add-ons
