### ISSUE TITLE
Can't seem to update TV shows; updating movies work fine

### ISSUE THREAD

**Issue by infinite-improbability-drive** [matthuisman/docker-kodi-headless#18]
I'm hoping to find some help with getting this container fully up and running on my Synology NAS.

I seem to have everything working properly for movies; I can set content type and information provider for folders in another instance of Kodi (in this case Windows, but also Android Nvidia Shield TV Pro boxes), and scan from the headless web app and have whole folders scraped very fast (compared to any other experience I've had updating libraries with Kodi).

I also seem to have configured both Sonarr and Radarr to send notifications to headless kodi, though I'm not quite sure if that's working properly.

As far as TV shows, I seem to be a bit stumped. Movies don't seem to have a problem with doing an initial scrape from the headless app once the folder is set from Kodi desktop app. Everything I've read says that Kodi headless doesn't quite like doing an initial scan. Though even after an initial scan, no matter what I do I can't seem to get Kodi headless to update TV shows on its own.

kodi.log, for more information:

https://pastebin.com/RQvExSAF

Any help would be very much appreciated! This seems to be the last piece of the puzzle I'm missing for my 'ideal' Kodi setup, almost!

**Comment by infinite-improbability-drive** [comment]
Small update: I might have a mismatch between scrapers between local and headless Kodi. I seem to be able to scrape some shows using 'refresh show and episodes' in headless Kodi.

**Comment by matthuisman** [comment]
https://github.com/matthuisman/docker-kodi-headless#install-add-ons should help now installing the correct scrapers and all their dependencies. Less reason to need to copy over userdata folders now :)
