### ISSUE TITLE
step-by-step guide for the first configuration

### ISSUE THREAD

**Issue by cap-blackbeard** [matthuisman/docker-kodi-headless#21]
Hello Matt,
is there a step-by-step guide for the first configuration of the container?
Specifically I want to ask how can I add the media sources to the container?
I copied the sources.xml file from my KODI installation and pasted it into the container. However, I don't get any data displayed in the web UI.

**Comment by matthuisman** [comment]
https://github.com/matthuisman/docker-kodi-headless/blob/master/docker-compose.yml has an example compose file you can use.

Otherwise, this kodi is the same as "Stock kodi" just without the gui....
so https://kodi.wiki/view/Main_Page is valid etc.

Cant help further than that sorry

**Comment by cap-blackbeard** [comment]
Thank you very much! The doker-compose.yml helped me.
The container is running.

I mounted the files to the host and added the volume to the container.  I also edited the source-xml. Now I see the files in the browser of Chorus2-web-ui. But the database scan doesn't work.

What am I doing wrong?

**Comment by matthuisman** [comment]
you'll need to set content for sources most likely from another instance of Kodi pointing to the same sql database

**Comment by cap-blackbeard** [comment]
Works. Thank you!
