### ISSUE TITLE
Error after most recent update

### ISSUE THREAD

**Issue by crb4** [matthuisman/docker-kodi-headless#22]
Had this working on Unraid however after docker update I am getting an error
'/usr/lib/kodi/kodi-x11: error while loading shared libraries: libpython3.6m.so.1.0: cannot open shared object file: No such file or directory'

**Comment by matthuisman** [comment]
What is your device?

**Comment by crb4** [comment]
> 
Amd64

**Comment by hernandito** [comment]
Getting same error... Kodi Docker in unRAID... on a Xeon server.

**Comment by matthuisman** [comment]
should be fixed shortly when https://github.com/matthuisman/docker-kodi-headless/actions finish :)

**Comment by hernandito** [comment]
Thank you! Please let us know when we OK to update the container.

**Comment by matthuisman** [comment]
ready now :)

**Comment by hernandito** [comment]
Works perfect. Thank you!!!

**Comment by matthuisman** [comment]
sweet :)
There is a Nexus build now too.

And also a new easier way to install addons directly
https://github.com/matthuisman/docker-kodi-headless#install-add-ons

**Comment by crb4** [comment]
Thanks from me too.
