### ISSUE TITLE
Nexus (v20)

### ISSUE THREAD

**Issue by Enrico2** [matthuisman/docker-kodi-headless#29]
Hi, I'm wondering if you're going to support version 20 (Nexus) soon. 
The version automatically upgraded on my Google TV, and the database has been migrated by that app. It would be good to have a headless version as well to run on the nas

**Comment by Enrico2** [comment]
Oh hey wait, sorry I think you already support it! I was thrown by the readme that has the matrix example

**Comment by matthuisman** [comment]
Yes. I've been supporting it since beta1 :) enjoy
