### ISSUE TITLE
Nexus-latest changes /config ownership to '911:1000' ignoring -e PIG/GID

### ISSUE THREAD

**Issue by tuxwielder** [matthuisman/docker-kodi-headless#31]
Hi Matt,

Looks like (re)pulling/rebuilding to Nexus-latest causes the ownership of the /config-folder to be changed to UID/GID '911/1000'. This is ignoring explicitly issued '-e PUID= -e PGID=' directives.

Stopping the container, reinstating folder ownership and starting the container seems to work though...

With kind regards,

Jeroen

**Comment by matthuisman** [comment]
i have just tried and PUID and PGID both working fine for me.
confirmed my mounted /config directory on host had its user and group changed when container started

**Comment by matthuisman** [comment]
actually, on my 2nd run I struck the 911 issue

**Comment by matthuisman** [comment]
seems random when it has issues and changes permission to 911.
I suspect it may be a bug from s6v3 legacy support.
Working on now changing the container to use proper s6v3

**Comment by matthuisman** [comment]
this seems to now be fixed in latest container using s6v3 :)

**Comment by Enrico2** [comment]
new container fixed this! Thanks @matthuisman
