### ISSUE TITLE
Add UI access via KasmVNC

### ISSUE THREAD

**Issue by rodneyshupe** [matthuisman/docker-kodi-headless#34]
Would it be possible to add UI access for making administration easier?  This may be very easy by utilizing the using a different base image "FROM ghcr.io/linuxserver/baseimage-kasmvnc:ubuntujammy" as illustrated in this docker file: https://github.com/linuxserver/docker-calibre/blob/master/Dockerfile

This would allow the user to interact with the UI via a web browser.  In the Calibre example, it maps the UI access to 8080 and 8181 for http and https respectively but those could be easily adjusted as to not interfere with Kodi.

**Comment by matthuisman** [comment]
No sorry. You might want to look at the other headless containers that
still create a gui. This container doesn't at all so vnc wouldn't be
possible

**Comment by rodneyshupe** [comment]
No worries. Would be able to share the docker file and I would try this myself.

**Comment by matthuisman** [comment]
It's all in this repo. Just select the branch
