### ISSUE TITLE
Omega Beta 1 build

### ISSUE THREAD

**Issue by KyleSanderson** [matthuisman/docker-kodi-headless#37]

**Comment by matthuisman** [comment]
i usually dont do builds until Beta

**Comment by KyleSanderson** [comment]
> i usually dont do builds until Beta

I respect that. All the quietvoid DoVi stuff is based on Omega so I've been in a weird spot for a long time. They bumped the database format in A3 so now it's do I want the latest fixes, or to have a working library.

I know that falls into a "not my problem", but it would be cool if the tag was supported.

**Comment by KyleSanderson** [comment]
Beta 1 shipped 4 days ago.

**Comment by matthuisman** [comment]
thanks! yup. ill try get onto this over the next few days.
Its not that simple as all their build dependencies change between releases etc

**Comment by matthuisman** [comment]
building now: https://github.com/matthuisman/docker-kodi-headless/actions/runs/6717984402
untested

**Comment by matthuisman** [comment]
omega images now available https://hub.docker.com/r/matthuisman/kodi-headless/tags

testing locally. seems ok
![image](https://github.com/matthuisman/docker-kodi-headless/assets/6225961/af88a828-1869-4171-a1b8-50ed6d021996)
![image](https://github.com/matthuisman/docker-kodi-headless/assets/6225961/3e737194-3f45-4bba-a336-54eaa86f0d85)

**Comment by KyleSanderson** [comment]
Thank you very much
