### ISSUE TITLE
Omega Beta 2

### ISSUE THREAD

**Issue by HeresJonny** [matthuisman/docker-kodi-headless#40]
Any chance of an update to accomodate for the recent database change to myvideos123? Thanks in advance for your great work!

**Comment by matthuisman** [comment]
is that latest Omega nightly? They should have a Beta 2 shortly right?

**Comment by matthuisman** [comment]
Omega B2 building now. https://github.com/matthuisman/docker-kodi-headless/actions/runs/7155938701
Should be on docker hub in 1 hour-ish
