### ISSUE TITLE
Add music sources to kodi library

### ISSUE THREAD

**Issue by JanvdW304** [matthuisman/docker-kodi-headless#41]
The headless installation of Kodi went smoothly, but I am unable to update the music collection with the music that's stored on an external harddisk.

In the docker-compose.yaml I have created a mapping to this hard disk, and that works: if I open the docker console (docker exec -it kodi-headless sh) I can request a directory list of this mapping ('ls /media ').

I then included a path substitution (as mentioned in the readme) in advancedsettings.xml. I have tried that in different ways, at this moment:
`  </pathsubstitution>
    <substitute>
      <from>smb://<user>:<password>@server ip>/<mnt>/<folder>/</from>
      <to>/media/</to>
    </substitute>
  </pathsubstitution>`

Finally, I also included a reference in the sources.xml, but that also produced no results:
`  <music>
    default pathversion="1"></default>
    <source>
      <name>Auto-mounted drives</name>
      <path pathversion="1">/media/</path>
      <allowsharing>true</allowsharing>
    </source>
  </music>`

Kodi itself works just fine, no error messages in the log. But when I refresh the library, Kodi indicates after 0 sec that it is ready.

How can I solve this?

**Comment by matthuisman** [comment]
nothing to do with headless.
You'll need to setup the scrapers externally so they get into the DB probably

**Comment by JanvdW304** [comment]
How can to setup the library scrapers externally? In my normal kodi installation I define the path to the library via the KODI GUI, but I can't doe this in the web interface

**Comment by matthuisman** [comment]
thats a limitation of their web gui i believe.
You'll need to use another kodi on windows or something, point it to the shared DB. add the library sources (these are stored in DB).

**Comment by JanvdW304** [comment]
Ah, right. I'll check that later. Thanks
