### ISSUE TITLE
Recently added Movies not updating

### ISSUE THREAD

**Issue by budmannxx** [matthuisman/docker-kodi-headless#42]
I've noticed an issue where my recently added movies are not showing in the Recently Added Movies section of the GUI.  This is happening in the headless webUI as well as all clients.  I was having this issue on 20.2, and it is still an issue after upgrading headless and clients to 20.3.

Weirdly, my newly added TV episodes do show up in the recently added section, so this is limited to an issue with just movies.  I have "update library on startup" enabled, but that shouldn't come into play here as I'm not restarting the headless docker container very often.  FWIW, in my Sonarr and Radarr, I have the connection to Kodi headless enabled, tested successfully, and the "update library on import & rename" setting enabled.

What can I do to resolve this?

**Comment by matthuisman** [comment]
are the movies actually scanned in?
ie. can be found under movies but just not recently added?
Is your date correct?

**Comment by budmannxx** [comment]
the movies are scanned in and available when I drill down into the Movies menu.  It's just the "recently added" on the main screen where they're missing.  I'll verify my date settings as soon as I can.  Odd that Sonarr/TV shows are working as expected though.

**Comment by matthuisman** [comment]
Oh. Maybe it's the created timestamps on the movie foles being wrong? If
they are auto downloading, check the program that downloads them

**Comment by budmannxx** [comment]
interesting.  on my SMB share from a Windows machine, I'm seeing the folder modified time as being in the past, 2024-01-15 11:53am.  The actual .mkv file shows 20**21**-04-25 10:50pm, and some other files (.nfo, .srt, etc.) have timestamps all in the past.  I also logged into the NAS directly and verified the timestamps there match what I'm seeing in Windows.  What are you thinking the issue may be with the timestamps?

I believe my system dates/times are all correct as well, but I'm not 100% sure I'm verifying in the right places.

**Comment by matthuisman** [comment]
kodis recently added uses the created or modified times i believe.
You may want to SQL into the DB and have a look at the rows for the new movies and see what dates kodi is seeing.
Follow that and you should find your issue.

Either way, its not a problem with docker / kodi docker as i do no mods around scanning etc

**Comment by budmannxx** [comment]
I agree with the closure due to this not being related to this docker container.  @matthuisman, as always, excellent support.  The issue was indeed that the file timestamps were off, from Radarr only.  Apparently Sonarr will update timestamps to "now" natively, but Radarr doesn't, and can only do this via custom script.  This comment got me to a solution: https://www.reddit.com/r/radarr/comments/tyexi0/comment/i3rt2yv/

**Comment by matthuisman** [comment]
great to hear you got it sorted
