### ISSUE TITLE
Omega Beta 3

### ISSUE THREAD

**Issue by dudel** [matthuisman/docker-kodi-headless#44]
Hi, if you have the time would you mind to update the docker image for Kodi Omega Beta 3? 

Thank you very much in advance!

**Comment by matthuisman** [comment]
I can't see any omega b3 release on XBMC GitHub

**Comment by dudel** [comment]
Oh damn, I'm sorry. I accidentally upgraded to nightly and it updated my db. Sorry for the confusion.

**Comment by matthuisman** [comment]
B3 is very close: https://github.com/xbmc/xbmc/pull/24690
Once that is merged and released, I'll update the containers :)
