### ISSUE TITLE
I need to install kodi on my host as well?

### ISSUE THREAD

**Issue by mattalexx** [matthuisman/docker-kodi-headless#45]
In the README it says I should "copy over the sources.xml from the host machine that you performed the initial library scan", but I don't see any mention of an installation on the host at all.

Is there some info missing from the README or am I being dense?

**Comment by matthuisman** [comment]
You may want to understand what Kodi is and what Kodi isn't first :)

I think you may be thinking this is something it is not

**Comment by mattalexx** [comment]
Thank you for your response. I've taking your suggestion and looked a bit more into using Kodi. My use case is this:

I have a file server on my LAN. It exports a NFS shares and runs docker containers.

Some time ago, I got tired of paying ten bucks a month to music streaming services, and set up a [Navidrome] music server running in one container. It provides a simple web interface, along with a Subsonic API, the latter of which I use more, streaming things to my phone, which runs [Symfonium]. Providing it my music library is as simple as configuring a read-only bind mount in docker.

This setup is ok, but there are some problems with Navidrome:

One, it does not support smart playlists ([yet](https://github.com/navidrome/navidrome/issues/1417)), and I tend to use those a lot. Symfonium does, but that's backwards. The client should not be the source of truth about my music library. 

Two, I would like to find a replacement that is more extensible. Frankly, if it was simpler to find or write a simple plugin to use as a sort of band-aid for the missing playlist feature, I might not have started looking to ditch Navidrome.

Three, this needs to be a self-hosted, open source solution. As I believe I've already made clear, I'm a cheapo. Also, call me paranoid, but I don't authenticate to corporate servers unless there's a good reason. I believe this disqualifies even the free Plex option.

Kodi seems to fit the bill to replace Navidrome as my music streaming server. It supports smart playlists, has an add-on marketplace, doesn't require me to log into a Kodi server. Plus, maybe I will use it for movies too at some point and kill my Jellyfin server.





Ok, so back to the original issue. It seems like the real problem is that Kodi's web interface simply doesn't have the ability to configure media sources like the main app does. If I want to avoid installing the main app, and I just want to install the web interface in a docker container, I'll need to provide my own `sources.xml`. Right?

I don't see why it should be necessary to install the full Kodi outside of Docker, just to grab a config file. The Kodi docs are GUI-centric and they don't provide a full example of `sources.xml`. I wonder if a simple template and some instructions should be provided here?

Please feel free to confirm/deny these assumptions. Thanks

[Navidrome]: https://www.navidrome.org/
[Symfonium]: https://symfonium.app/
[smart playlists]: https://kodi.wiki/view/Smart_playlists

**Comment by matthuisman** [comment]
kodi is not made to be headless. this is essentially a hack. you cant do a lot of stuff via web interface. but if you can work out how to create the sources etc yourself. then go for gold.
I know with setting content - that stores the scraper stuff in the DB. pretty sure your going to need a real instance to do all of that

**Comment by mattalexx** [comment]
Yes, I was starting to get that impression, thank you for your confirmation. 

Ok, I think I'm going to just use [Smart Playlist beets plugin] and that will be fine :+1:
