### ISSUE TITLE
Omega 3 Update Failed -  ERROR: Unable to create GUI. Exiting

### ISSUE THREAD

**Issue by ryanstevens00** [matthuisman/docker-kodi-headless#47]
I updated to Omega beta 3 and when kodi is trying to start I get the following error "ERROR: Unable to create GUI. Exiting". 

Also the web inteface is not accessible.  

Is there a configuration setting I am missing to get this started?

**Comment by matthuisman** [comment]
did Omega Beta 2 work fine? Same advanced settings etc?

**Comment by matthuisman** [comment]
i can reproduce so suspect the path isnt working with Omega 3 and needs to be looked at.
Ill revert to Omega b2 for now

**Comment by ryanstevens00** [comment]
Yes Omega b2 worked just fine with the save advanced settings, etc.

**Comment by matthuisman** [comment]
ill try get it fixed and out again today

**Comment by matthuisman** [comment]
its building now. should be pushed in about an hour :)

**Comment by matthuisman** [comment]
fixed now. please pull latest omega image. thanks for letting me know
