### ISSUE TITLE
Websocks Connection Lost

### ISSUE THREAD

**Issue by jsmith432** [matthuisman/docker-kodi-headless#49]
I installed the container and am getting a "websocks connection lost" error. The only change I made was on port "myport:8080", which I am exposing to another port. There are no messages in the container log, and it isn't reading the database updates, although they loaded after restart. Is there another log that I can look into? Any other steps or recommendation?

**Comment by matthuisman** [comment]
did you update the advanced settings port to match?
Otherwise there webapp will be trying to connect to wrong port

**Comment by matthuisman** [comment]
ive updated https://github.com/matthuisman/docker-kodi-headless readme.

Make external port and internal port match and then update / override advancedsettings with the ports

**Comment by jsmith432** [comment]
That is not the issue, though. The advancedsettings.xml port is the docker host port. If I change that I also need to change "myport:myport", and that doesn't work either. 
I changed  <webserverport>9020</webserverport>, that changed the "internal" port to "9020", which made the webui inaccessible. 
I then change the port map to 9020:9020 and that made the UI acessible again but my library did not load and the same error happened.

**Comment by matthuisman** [comment]
not sure sorry. keep trying and hopefully you figure it out :)

**Comment by jsmith432** [comment]
Looks like there is something hardcoded to port 8080 and it wont work if you change the "exposed" port.

**Comment by matthuisman** [comment]
Again, did you change both external and internal to be the same and then
update advancedsettings?? Their web GUI uses Ajax to talk to itself. If it
thinks it's running on port 8080, it'll try open a connection from your
browser to 8080 = fail.

**Comment by jsmith432** [comment]
I tried 9020:9020, changing the port to 9020 in advanced settings. It loads, but it gives the same websocket error. Ultimately, I can only make it work if it is all 8080.

**Comment by matthuisman** [comment]
Check the requests the website is trying to make using Chrome web tools or
something

**Comment by jsmith432** [comment]
with 9020:9020 and advancedsettings 9020 for webport: 
![Screenshot 2024-03-15 161408](https://github.com/matthuisman/docker-kodi-headless/assets/4900328/b64e0ed4-97bd-4c8e-94fe-7fe30ad3ac0c)


with 8080:8080 and advancedsettings 8080 for webport: 
![Screenshot 2024-03-15 161550](https://github.com/matthuisman/docker-kodi-headless/assets/4900328/ffb433bf-6c30-4088-b2b9-054b0b1092c6)

**Comment by matthuisman** [comment]
oh. the websocket port != the web server port.
There are two ports

I host my web server on 8081 and websocket on 9090
**- 8081:8080
- 9090:9090**

![image](https://github.com/matthuisman/docker-kodi-headless/assets/6225961/6fe60202-8931-4e36-8edd-a0243665ac49)

**Comment by matthuisman** [comment]
i actually just had a play and it appears webserverport advanced settings doesnt actually change the port.
Kodi still runs it on 8080 (maybe a kodi bug)

Anyway, for that port, its find to forward a different external.
eg. 9020:8080

But for the tcpport, you want them to match.
So 9090:9090

**Comment by matthuisman** [comment]
ignore above, my advancedsettings.xml wasnt overriding the default.
Once i got that working, I can change the internal port to 8081

and then use
8081:8081 (webserver)
9090:9090 (tcp / websocket)

**Comment by jsmith432** [comment]
Both these scenarios do not work for me: 

Scenario 1:  9020:9020
Docker: 
![Screenshot 2024-03-16 221254](https://github.com/matthuisman/docker-kodi-headless/assets/4900328/6c0aa1b5-b1ec-46a5-bf56-6dc714941853)
Advanced:
![Screenshot 2024-03-16 221302](https://github.com/matthuisman/docker-kodi-headless/assets/4900328/b09540e4-3d21-4c59-ac10-4cf48623505b)
Error:
![Screenshot 2024-03-16 221309](https://github.com/matthuisman/docker-kodi-headless/assets/4900328/8583091e-8d95-40b2-a273-4cab2f667723)

Scenario 2: 9020:9020
Docker
![Screenshot 2024-03-16 221115](https://github.com/matthuisman/docker-kodi-headless/assets/4900328/dc0684d6-4bf9-431c-998e-f58d1610d7ea)
Advanced:
![Screenshot 2024-03-16 221151](https://github.com/matthuisman/docker-kodi-headless/assets/4900328/6de0b4cd-b722-477c-bf27-321a8fe05f4c)
Error:
![Screenshot 2024-03-16 220901](https://github.com/matthuisman/docker-kodi-headless/assets/4900328/528d76b5-5884-499b-8e93-7337a6236b3a)

**Comment by matthuisman** [comment]
are you sure your advancedsettings are overriding etc?
Have you checked the kodi log. that spits out the advanced settings and where its starting the webserver etc

/config/.kodi/temp/kodi.log

**Comment by jsmith432** [comment]
Yes, it is overriding. If I did 9020:9020 and it didn't the UI wouldn't come up at all but I do see it on the kodi log.

**Comment by matthuisman** [comment]
what version of kodi using?
Im using Nexus and could change ports fine

**Comment by matthuisman** [comment]
can you try 8081 just for fun and see if works?

**Comment by matthuisman** [comment]
ok. so the web interface is hard-coded to 9090 - it doesnt check the actual kodi setting (https://github.com/xbmc/chorus2/blob/4f360685fb9c000c3e5db6b389eb9b83b8d678dc/src/js/app.coffee#L8)

So, if using the Chorus2 interface, you will need to stick with 9090:9090 for tcpport

**Comment by matthuisman** [comment]
also, looks like the webinterface has its own addon settings:
http://nas.kodi.mjh.nz:9020/addons/webinterface.default/#settings/web

Maybe there is a setting in there that can fix the issue for you

**Comment by matthuisman** [comment]
maybe tcpport isnt even related to this websocket. I think the websocket is part of the WEB INTERFACE addon. Not kodi itself.

tcpport i believe may just be a port to use JSON RPC (not websocket)

So, maybe your getting a conflict.
Try setting tcpport to just something random. dont worry about forwarding port for it.
Then keep 9090:9090 for the websocket and make sure the interface setting for websocket is 9090

**Comment by jsmith432** [comment]
I tested both nexus and omega. For the time being I moved the other container from 8080, so I can at least try to test kodi-headless in 8080 for the time being. Somewhere maybe on the initialization of the first time it wrote 8080 and I have to complete delete all and restart from scratch but will do that later. Thanks for your patience.

**Comment by matthuisman** [comment]
Also try without shared volume (ie fresh)
Make sure no old settings etc causing issues

**Comment by HeresJonny** [comment]
Similar problem here. I chose the non-standard port 8086 instead of 8080. While connection to the webgui basically works, some actions like changing settings trigger a "lost websocket" message while the GUI keeps on being accessible. I can't teeö of tjere adverse affects so I haven't pursued it further. One thing I noticed is that I can't seem to change the setting for addon updates to use "unknown sources". It always stays deactivated.

**Comment by jonwaland** [comment]
I'm running kodi (nexus previously, and now omega) with the following:

```
services:
  kodi:
    container_name: kodi
    image: matthuisman/kodi-headless:Omega
    restart: unless-stopped
    volumes:
      - /home/walaj/docker/kodi/config/.kodi:/config/.kodi
    ports:
      - 9777:9777/udp
      - 9090:9090
      - 8081:8080
    environment:
      - TZ=Australia/Sydney
      - PGID=1000
      - PUID=1000
```

I **don't** have JSONRPC set in the advancedsettings xml.

I **don't** have issues with Chorus2. The only setting that is required to let Chorus2 work correctly (for me) is to enable Reverse Proxy support. This may or may not be the issue here....
