### ISSUE TITLE
SSL on WebServer

### ISSUE THREAD

**Issue by smarthome-enthusiast** [matthuisman/docker-kodi-headless#50]
Is there a way to enable SSL for the web server?

I have already copied the certificate and key (PEM format, named server.pem and server.key respectively) to userdata folder and enabled it under Settings > Services > Control but I wouldn't be able to connect to the web server. Restarting the docker would get it to fallback to HTTP. I have also looked at guisettings.xml to enable it but same result.

Am I missing something? Any help would be appreciated.

**Comment by matthuisman** [comment]
should be the same process on doing it with normal (not headless) Kodi. have you got that working?

**Comment by matthuisman** [comment]
ill have a play tonight and figure it out :)
https was added with this PR: https://github.com/xbmc/xbmc/pull/13165/files

**Comment by matthuisman** [comment]
hang on, do you need to use a domain name for https?
whats your cert for? a domain?

**Comment by matthuisman** [comment]
yes i know about certs. But your still accessing it via its IP in the screenshots
Did you try using the domain name to access it?

**Comment by smarthome-enthusiast** [comment]
Tried using both the domain name and IP.

![image](https://github.com/matthuisman/docker-kodi-headless/assets/143326320/a2343ac6-0857-493f-bdd8-447ceef067f0)

**Comment by matthuisman** [comment]
ok. i think the issue is my docker container is just using libmicrohttpd-dev from ubuntu which i believe isnt compiled with https.

Kodi has a makefile to build it here:
https://github.com/xbmc/xbmc/blob/master/tools/depends/target/libmicrohttpd/Makefile#L4
but think it skips that if it finds its own

So asking them how I can force it to build as I believe if I dont have libmicrohttpd-dev, it wont find it and then fail.

**Comment by smarthome-enthusiast** [comment]
Okay, thanks. Will wait patiently.

**Comment by matthuisman** [comment]
after googling I found:
https://lists.nongnu.org/archive/html/libmicrohttpd/2010-01/msg00005.html

```
openssl genrsa 1024 > server.key
openssl req -new -x509 -nodes -sha1 -days 365 -key server.key > server.cert
cat server.cert server.key > server.pem
```

Copied the server.pem and server.key into userdata

then added to advancedsettings.xml
```
    <services>
        <webserverssl>true</webserverssl>
        ....
```

Restarted and I have https server

**Comment by matthuisman** [comment]
have updated the readme and also added some example files to the branches

**Comment by smarthome-enthusiast** [comment]
> then added to advancedsettings.xml
> 
> ```
>     <services>
>         <webserverssl>true</webserverssl>
>         ....
> ```
> 
> Restarted and I have https server

That worked. Thank you.

**Comment by matthuisman** [comment]
Great :) so the missing thing for you was just the advanced setting?
My issue was the cert I generated wasnt like by the server. Cant remember what options i was using.
But once I switched to the above commands - it was happy

**Comment by smarthome-enthusiast** [comment]
sorry for the late reply, I think it was. I didn't think about the guisettings.xml Setting Conversion section of the wiki. Just tried Web UI and guisettings.xml.
