### ISSUE TITLE
Is it possible to run this with sqlite instead

### ISSUE THREAD

**Issue by tian2992** [matthuisman/docker-kodi-headless#51]
Id love to use this for local hosting my files. However id rather not run Yet another MySQL any chance to use integrated db and bind to a local volume for easy bootstrapping? I checked the docker file and Compose but still not sure on how to run it as a sqlite.

**Comment by matthuisman** [comment]
why?
You lose the benefit of a shared DB = the entire purpose of this headless.

**Comment by tian2992** [comment]
I just need a single user to access it via network API. no need for high concurrency or sharing the DB files across the network. And I know i could just run Kodi on the server but i dont need GUI there...

**Comment by matthuisman** [comment]
https://kodi.wiki/view/Databases kodi stores its dbs in kodi/userdata so just mount that to a volume with -v <path to data>:/config/.kodi

Your going to struggle to add media sources etc via the web gui, but thats a kodi issue - not a headless issue.

good luck
