### ISSUE TITLE
Quick question on the Thumbnails folder...

### ISSUE THREAD

**Issue by bossanova808** [matthuisman/docker-kodi-headless#53]
I noticed my docker config backups growing quite a bit and looking in to it I realise my two Kodi headless containers are the reason - and specifically the `userdata/Thumbnails` folders are growing.

Is there any reason not to either periodically delete that folder - I mean, a headless install doesn't need Thumbnails right?

I presume Kodi will re-create the folder if it's not there (and continue to create thumbnails), but there's no point keeping them around right?  (I let each client make its own thumbs, I don't e.g. use path substitution or anything).

**Comment by matthuisman** [comment]
im not adding new features to kodi itself.
Maybe google and see if there is an advanced setting to disable kodi thumbnail creation?

And headless does use them if you go into the web interface....
I thought they were only created then (on demand)
but maybe they are created during scraping too

**Comment by matthuisman** [comment]
are you using the default advanced settings?
https://github.com/matthuisman/docker-kodi-headless/blob/Omega/root/defaults/advancedsettings.xml

you can see it does a bit of stuff related to thumbs that may help
I use those same settings and havnt noticed anything too large

**Comment by bossanova808** [comment]
Yeah I think it must happen with scraping.

I'll tackle it another way - there's no harm having them there really (plenty of disk space) - but I'll exclude them from the backups which is really just to have the key config etc.

I am not using the default no - not sure it was around when I set this up, but will merge in appropriate stuff now

Thanks!

**Comment by matthuisman** [comment]
yes, it could be the extractthumbs doing it. that would slow down scraping as well

**Comment by matthuisman** [comment]
pretty sure, i dont get any default images until i load the gui

If still want cleaning - just add a service addon to do it :)
There may even be one that already exists
