### ISSUE TITLE
How to add a repository?

### ISSUE THREAD

**Issue by jonwaland** [matthuisman/docker-kodi-headless#55]
I know you have a patch/process for adding addons "from enabled repositories" - how do I add a repository (to a headless install)?

**Comment by matthuisman** [comment]
Look at the readme to install add addons

**Comment by matthuisman** [comment]
Repos are add-ons. So use the cmdline or extract the repo into add-ons dir.
Restart Kodi and that repo then enabled. The. Use cmdline to install
add-ons from that repo.

**Comment by jonwaland** [comment]
oh. been doing this for years, and didn't make that distinction.  just added the URL or zip file and went from there. 

Thanks.

**Comment by matthuisman** [comment]
Yeh. Just need to download that and transfer
