### ISSUE TITLE
Which file do i need to copy for the Video Versions settings?

### ISSUE THREAD

**Issue by danmed** [matthuisman/docker-kodi-headless#58]
I've configured anotehr client with the Video Versions settings that i'd like from this guide

https://kodi.wiki/view/Video_versions

But i don't know which file i need to copy to my headless docker container to get it to do what i want.. 

Any ideas?

**Comment by matthuisman** [comment]
im not familiar with video versions sorry. Im pretty sure its all done in the SQL database

If you mean the settings for it, kodi stores all its settings in guisettings.xml im pretty sure
