### ISSUE TITLE
Websockets port needs changing in Chorus2's  /#settings/web menu also.

### ISSUE THREAD

**Issue by kelvtech-co-uk** [matthuisman/docker-kodi-headless#59]
I'm mostly working now thanks to your great work!  Just want to share that I needed to move the websocket port off 9090 as it clashed with another container.  I amended the advancedsettings.xml file as per your instructions but Chorus2 still complained every minute about "Lost websocket connection" along with "Attempting websockets reconnect".  I eventually tracked this down to needing to also amend Chorus2's setting which looks to be independent to everything else.

![image](https://github.com/user-attachments/assets/895ea65d-59c0-4a1b-8240-8c9af5d1696a)

Once this was done and the container restarted the error messages went away.

**Comment by matthuisman** [comment]
yes, think we found that out on https://github.com/matthuisman/docker-kodi-headless/issues/49 
I've added a note on readme
