### ISSUE TITLE
Not build for audio out on server, correct? 

### ISSUE THREAD

**Issue by Uatschitchun** [matthuisman/docker-kodi-headless#62]
These headless docker images are not build to output audio on the server, correct?

I'd like to play audio on the headless instance and adapt it to a snapcast instance for to have multiroom audio.

Have it working now with a normal kodi install, but I don't need the UI. Easiest would probably be to just compile my own kodi using your patches, wouldn't it?

Has someone tried or adapted the headless docker with giving access to /dev/snd?

**Comment by matthuisman** [comment]
no audio sorry, there is another headless docker floating around which i think has audio. i cant recall where though

And yes - maybe just compile yourself :)
