### ISSUE TITLE
Clean Library Request

### ISSUE THREAD

**Issue by Andystew94** [matthuisman/docker-kodi-headless#8]
Hi matthuisman, I am successfully running this on my NAS using Docker however while the "Update Library" works, "Clean Library" does not remove duplicate entries when prompted by Sonarr/Radarr. Wondering if you have experienced this issue?
NOTE: All Kodi instances are using a shared MySQL database.

**Comment by Andystew94** [comment]
This does work if I connect Sonarr/Radarr to another instance of Kodi in the house. Only the headless instance seems to have an issue completing the request.

**Comment by matthuisman** [comment]
i use this same container and clean works fine for me
youd need to check logs etc and see whats going on
